module.exports = {
  SUCCESS: 'SUCCESS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXISTS: 'USER_EXISTS',
  USER_VERIFIED: 'USER_VERIFIED',
  INVALID_DATA: 'INVALID_DATA',
  DUPLICATE_USER: 'DUPLICATE_USER',
  ERROR: 'ERROR'
}
