module.exports = {
  SUCCESS: 'SUCCESS',
  INVALID_DATA: 'INVALID_DATA',
  DUPLICATE_USER: 'DUPLICATE_USER',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  VALID_USERNAME_AND_PASSWORD: 'VALID_USERNAME_AND_PASSWORD',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  NOT_FOUND: 'NOT_FOUND',
  ERROR: 'ERROR'
}
